# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "deseq2_transform"
description: Transform DESeq2 .txt files into MultiQC-formatted _mqc.tsv files with proper headers
keywords:
  - deseq2
  - multiqc
  - qc
  - aggregation
tools:
  - custom:
      description: |
        Custom module to transform DESeq2 output files for MultiQC visualization.
        Finds DESeq2 PCA and sample distance .txt files and prepends MultiQC headers
        to create properly formatted _mqc.tsv files.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - run_dir:
      type: directory
      description: Directory containing DESeq2 output files from a pipeline run
      pattern: "*/"
  - pca_header:
      type: file
      description: MultiQC header file for PCA plots
      pattern: "*.txt"
  - clustering_header:
      type: file
      description: MultiQC header file for clustering/distance plots
      pattern: "*.txt"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - multiqc_files:
      type: file
      description: MultiQC-formatted TSV files with headers
      pattern: "*_mqc.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@seqera-ai"
maintainers:
  - "@seqera-ai"
